name: MyOwnAction

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Example print OK.
    - name: github-action-publish-binaries
      uses: skx/github-action-publish-binaries@release-1.2
      env:
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}


